"""
Level-of-evidence classification on the JBI / AACN hierarchy.

The hierarchy itself is a *scheme* — an ordering of study designs — and is used
here by name with attribution. The published instruments' own tables are not
reproduced; the design signals below and the wording of every explanation are
this tool's, which is the distinction that keeps the feature clear of the
instrument publishers' reproduction terms. See `appraisal.py` for the same
distinction applied to checklists, where it matters considerably more.

Levels used (matching the user's stated criteria):

    I    systematic reviews, meta-analyses, randomised controlled trials
    II   well-designed controlled trials without randomisation
    III  well-designed cohort or case-control analytic studies
    IV   descriptive or qualitative studies
    V    expert consensus and clinical guidelines

Two classifications carry more weight than they look:

**"Review" is not "systematic review".** PubMed's `Review` publication type
covers narrative reviews, which are not evidence-based literature under the
user's own criteria. Software that treats `Review` as Level I inflates the
apparent strength of a whole matrix, and it is the single most common
misclassification in automated EBP tooling. Here `Review` alone lands at Level
V and says why.

**Editorials, letters, comments and retracted articles are not graded at all.**
They get `EXCLUDED`, not Level V, because the user's criteria state plainly
that opinion pieces do not qualify as evidence — and a Level V label would let
them pass a "minimum level" filter.
"""

from __future__ import annotations

import re

from ..models import EvidenceLevel, Work

CITATION = (
    "Levels follow the Joanna Briggs Institute and AACN evidence hierarchies "
    "as described in the project's stated research criteria. Design signals and "
    "explanations are generated by this tool, not reproduced from either "
    "instrument."
)

# Publication types, lowercased, that decide a level outright. PubMed assigns
# these from the article itself, which makes them the most reliable signal
# available — more so than title or abstract wording.
_PT_RULES: list[tuple[EvidenceLevel, tuple[str, ...], str]] = [
    (EvidenceLevel.EXCLUDED,
     ("retracted publication", "retraction of publication", "editorial", "letter",
      "comment", "news", "newspaper article", "biography", "interview",
      "personal narrative", "published erratum", "expression of concern"),
     "indexed as an opinion, correspondence or corrective item, which the "
     "project's criteria exclude from evidence-based literature"),

    (EvidenceLevel.LEVEL_I,
     ("meta-analysis", "systematic review", "randomized controlled trial",
      "randomised controlled trial", "pragmatic clinical trial",
      "equivalence trial", "adaptive clinical trial"),
     "indexed as a systematic review, meta-analysis or randomised controlled "
     "trial"),

    (EvidenceLevel.LEVEL_II,
     ("controlled clinical trial", "clinical trial, phase iii",
      "clinical trial, phase ii", "clinical trial", "non-randomized controlled"),
     "indexed as a controlled trial without stated randomisation"),

    (EvidenceLevel.LEVEL_III,
     ("observational study", "comparative study", "multicenter study",
      "twin study", "validation study", "evaluation study"),
     "indexed as an analytic observational study"),

    (EvidenceLevel.LEVEL_IV,
     ("case reports", "case report", "cross-sectional studies",
      "qualitative research", "survey"),
     "indexed as a descriptive, case or qualitative report"),

    (EvidenceLevel.LEVEL_V,
     ("practice guideline", "guideline", "consensus development conference",
      "consensus development conference, nih", "review", "scoping review",
      "narrative review"),
     "indexed as a guideline, consensus statement or non-systematic review"),
]

# Title and abstract signals, used only when publication types are absent or
# inconclusive — which is the normal case for records imported from an export
# rather than retrieved from PubMed.
_TEXT_RULES: list[tuple[EvidenceLevel, tuple[str, ...], str]] = [
    (EvidenceLevel.LEVEL_I,
     (r"\bsystematic review\b", r"\bmeta-?analys[ie]s\b",
      r"\brandomi[sz]ed controlled trial\b", r"\brandomi[sz]ed clinical trial\b",
      r"\bRCT\b", r"\bumbrella review\b", r"\bcochrane review\b",
      r"participants were randomi[sz]ed", r"\bdouble-?blind,? randomi[sz]ed\b"),
     "the title or abstract describes a systematic review, meta-analysis or "
     "randomised trial"),

    (EvidenceLevel.LEVEL_II,
     (r"\bquasi-?experimental\b", r"\bnon-?randomi[sz]ed (?:controlled )?trial\b",
      r"\bcontrolled before-?and-?after\b", r"\binterrupted time series\b",
      r"\bpre-?post (?:test )?design\b", r"\bcomparison group\b"),
     "the title or abstract describes a controlled design without randomisation"),

    (EvidenceLevel.LEVEL_III,
     (r"\bcohort stud", r"\bprospective cohort\b", r"\bretrospective cohort\b",
      r"\bcase-?control\b", r"\bnested case-?control\b",
      r"\blongitudinal (?:study|analysis)\b", r"\bmatched controls?\b"),
     "the title or abstract describes a cohort or case-control design"),

    (EvidenceLevel.LEVEL_IV,
     (r"\bcross-?sectional\b", r"\bdescriptive stud", r"\bqualitative\b",
      r"\bphenomenolog", r"\bgrounded theory\b", r"\bethnograph",
      r"\bthematic analysis\b", r"\bcase series\b", r"\bsurvey\b",
      r"\bfocus group", r"\bsemi-?structured interview", r"\bchart review\b",
      r"\bmixed-?methods\b", r"\bcontent analysis\b"),
     "the title or abstract describes a descriptive, survey or qualitative "
     "design"),

    (EvidenceLevel.LEVEL_V,
     (r"\bclinical practice guideline\b", r"\bpractice guideline\b",
      r"\bconsensus statement\b", r"\bposition statement\b",
      r"\bexpert (?:opinion|consensus|panel)\b", r"\brecommendations? (?:for|on)\b",
      r"\bnarrative review\b", r"\bliterature review\b", r"\bintegrative review\b",
      r"\bstate of the science\b"),
     "the title or abstract describes a guideline, consensus statement or "
     "non-systematic review"),
]

_OPINION_TEXT = (
    r"\beditorial\b", r"^letter to the editor", r"\bcommentary\b",
    r"\bopinion\b", r"\bin (?:this|my) view\b", r"\breflections? on\b",
)


def classify(work: Work) -> tuple[EvidenceLevel, str]:
    """Return the level and a plain-language reason for it.

    The reason string goes verbatim into the evidence matrix and the audit
    document, so the user can see *why* each source was graded as it was and
    override it — an unexplained grade is not defensible to a reviewer.
    """
    if work.retracted:
        return (
            EvidenceLevel.EXCLUDED,
            "the record is marked retracted, so it cannot support a claim "
            "regardless of its original design",
        )

    types = [t.strip().lower() for t in work.publication_types if t and t.strip()]
    haystack = f"{work.title}\n{work.abstract}".lower()

    # A systematic review indexed *also* as "Review" must not be pulled down to
    # Level V, so the specific rules are checked in hierarchy order and the
    # first match wins.
    for level, needles, reason in _PT_RULES:
        matched = [n for n in needles if any(n == t or n in t for t in types)]
        if not matched:
            continue
        if level is EvidenceLevel.LEVEL_V and "review" in matched:
            # Distinguish a genuine systematic review that PubMed also tagged
            # "Review" from a narrative review that carries only that tag.
            if re.search(r"\bsystematic review\b|\bmeta-?analys[ie]s\b", haystack):
                return (
                    EvidenceLevel.LEVEL_I,
                    "indexed as a review, and the title or abstract identifies it "
                    "as a systematic review or meta-analysis",
                )
            return (
                EvidenceLevel.LEVEL_V,
                "indexed only as a review, with nothing identifying it as a "
                "systematic review — narrative reviews sit at Level V, not "
                "Level I",
            )
        return (level, f"{reason} ({', '.join(sorted(matched))})")

    for level, patterns, reason in _TEXT_RULES:
        for pattern in patterns:
            if re.search(pattern, haystack, re.IGNORECASE):
                return (level, f"{reason} (matched “{_readable(pattern)}”)")

    for pattern in _OPINION_TEXT:
        if re.search(pattern, haystack, re.IGNORECASE | re.MULTILINE):
            return (
                EvidenceLevel.EXCLUDED,
                "the title or abstract reads as an editorial or opinion piece",
            )

    # Government and agency reports with no design signal are guidance
    # documents, which the hierarchy places at Level V.
    if work.work_type.value in ("report", "guideline") or any(
        a.is_group for a in work.authors
    ):
        return (
            EvidenceLevel.LEVEL_V,
            "an agency or organisational publication with no stated study "
            "design, graded as guidance rather than primary research",
        )

    return (
        EvidenceLevel.UNGRADED,
        "no publication type or design wording was found; grade this by hand "
        "after reading the methods section",
    )


def apply(work: Work) -> Work:
    """Classify in place, leaving any grade the user set by hand alone."""
    if work.level_reason.startswith("Set by hand"):
        return work
    work.level, work.level_reason = classify(work)
    return work


def apply_all(works: list[Work]) -> list[Work]:
    return [apply(w) for w in works]


def set_by_hand(work: Work, level: EvidenceLevel, note: str) -> Work:
    """Record a user override, marked so re-classification will not undo it."""
    work.level = level
    work.level_reason = f"Set by hand: {note}".strip()
    return work


def meets_minimum(work: Work, minimum: str) -> bool:
    """True when a work is at or above the project's minimum level.

    `EXCLUDED` and `UNGRADED` never pass. An ungraded record failing the filter
    is deliberate: it means "read this and decide", not "include it quietly".
    """
    if work.level in (EvidenceLevel.EXCLUDED, EvidenceLevel.UNGRADED):
        return False
    try:
        floor = EvidenceLevel(minimum)
    except ValueError:
        return True
    return work.level.rank <= floor.rank


def summarise(works: list[Work]) -> dict[str, int]:
    """Counts per level, for the matrix header and the PRISMA narrative."""
    counts: dict[str, int] = {}
    for work in works:
        counts[work.level.value] = counts.get(work.level.value, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: EvidenceLevel(kv[0]).rank))


def _readable(pattern: str) -> str:
    """Turn a regex back into something printable for the audit trail."""
    text = pattern
    for token, replacement in (
        (r"\b", ""), (r"(?:", "("), (r"[sz]", "s"), (r"-?", "-"),
        (r"[ie]s", "es"), (r"?", ""), ("^", ""),
    ):
        text = text.replace(token, replacement)
    return re.sub(r"[\\()|]", "", text).strip()
